const constants = {
  SELECT_CITY: 'SELECT_CITY',
  MOVE_MAP: 'MOVE_MAP',
  LOADED_POLYGONS: 'LOADED_POLYGONS',
  HOVER_AREA: 'HOVER_AREA',
  UNHOVER_AREA: 'UNHOVER_AREA',
  HOVER_TRACT: 'HOVER_TRACT',
  UNHOVER_TRACT: 'UNHOVER_TRACT',
  SELECT_AREA: 'SELECT_AREA',
  UNSELECT_AREA: 'UNSELECT_AREA',
  SELECT_TRACT: 'SELECT_TRACT',
  UNSELECT_TRACT: 'UNSELECT_TRACT',
  SELECT_TRACT_VIEW: 'SELECT_TRACT_VIEW',
};

export default constants;
