
export default {
  // selectedArea: null,
  // selectedCategory,
  selectedCity: 168,
  selectedArea: null,
  hoveredArea: null,
  selectedTract: null,
  hoveredTract: null,
  // selectedGrade: null,
  // selectedText,
  // showADScan,
  // showADSelections,
  // showContactUs: false,
  // showCityStats: true,
  // showFullHOLCMaps,
  // showHOLCMaps,
  // showNationalLegend: true,
  // showDataViewerFull,
  // adSelections: [],
  // areaDescriptions: null,
  // loadingCity: null,
  // adScan,
  map: {
    zoom: 12,
    center: [37.55, -77.45],
    bounds: [],
  },
  //   aboveThreshold: false,
  //   visibleRasters: [],
  //   visibleRasterPolygons: [],
  //   selectableRasterBoundaries: [],
  //   visibleBoundaries: [],
  //   visiblePolygons: [],
  //   highlightedPolygons: [],
  //   loadingPolygonsFor: [],
  //   userPosition: null,
  //   geolocating: false,
  //   sorting: false,
  //   sortingPossibilities: [],
  //   sortingLatLng: [],
  // },
  // searchingADsFor: null,
  // adSearchHOLCIds: [],
  // cities: Cities,
  // formsMetadata: FormsMetadata,
  // dimensions,
  // initialized: false,
  // donutCityMarkers: false,
};
